/**
 * @file fd_test.c
 *
 * @brief This source file was generated by cantools version 40.2.2 Tue Aug  4 16:27:12 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "fd_test.h"

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int fd_test_fd_test_pack(
    uint8_t *dst_p,
    const struct fd_test_fd_test_t *src_p,
    size_t size)
{
    if (size < 64u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 64);

    dst_p[0] |= pack_left_shift_u32(src_p->fd_test_counter, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->fd_test_counter, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->fd_test_counter, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->fd_test_counter, 24u, 0xffu);
    dst_p[8] |= pack_left_shift_u32(src_p->fd_test_byte8, 0u, 0xffu);
    dst_p[9] |= pack_right_shift_u32(src_p->fd_test_byte8, 8u, 0xffu);
    dst_p[10] |= pack_right_shift_u32(src_p->fd_test_byte8, 16u, 0xffu);
    dst_p[11] |= pack_right_shift_u32(src_p->fd_test_byte8, 24u, 0xffu);
    dst_p[32] |= pack_left_shift_u32(src_p->fd_test_byte32, 0u, 0xffu);
    dst_p[33] |= pack_right_shift_u32(src_p->fd_test_byte32, 8u, 0xffu);
    dst_p[34] |= pack_right_shift_u32(src_p->fd_test_byte32, 16u, 0xffu);
    dst_p[35] |= pack_right_shift_u32(src_p->fd_test_byte32, 24u, 0xffu);
    dst_p[60] |= pack_left_shift_u32(src_p->fd_test_byte60, 0u, 0xffu);
    dst_p[61] |= pack_right_shift_u32(src_p->fd_test_byte60, 8u, 0xffu);
    dst_p[62] |= pack_right_shift_u32(src_p->fd_test_byte60, 16u, 0xffu);
    dst_p[63] |= pack_right_shift_u32(src_p->fd_test_byte60, 24u, 0xffu);

    return (64);
}

int fd_test_fd_test_unpack(
    struct fd_test_fd_test_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 64u) {
        return (-EINVAL);
    }

    dst_p->fd_test_counter = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->fd_test_counter |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->fd_test_counter |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->fd_test_counter |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->fd_test_byte8 = unpack_right_shift_u32(src_p[8], 0u, 0xffu);
    dst_p->fd_test_byte8 |= unpack_left_shift_u32(src_p[9], 8u, 0xffu);
    dst_p->fd_test_byte8 |= unpack_left_shift_u32(src_p[10], 16u, 0xffu);
    dst_p->fd_test_byte8 |= unpack_left_shift_u32(src_p[11], 24u, 0xffu);
    dst_p->fd_test_byte32 = unpack_right_shift_u32(src_p[32], 0u, 0xffu);
    dst_p->fd_test_byte32 |= unpack_left_shift_u32(src_p[33], 8u, 0xffu);
    dst_p->fd_test_byte32 |= unpack_left_shift_u32(src_p[34], 16u, 0xffu);
    dst_p->fd_test_byte32 |= unpack_left_shift_u32(src_p[35], 24u, 0xffu);
    dst_p->fd_test_byte60 = unpack_right_shift_u32(src_p[60], 0u, 0xffu);
    dst_p->fd_test_byte60 |= unpack_left_shift_u32(src_p[61], 8u, 0xffu);
    dst_p->fd_test_byte60 |= unpack_left_shift_u32(src_p[62], 16u, 0xffu);
    dst_p->fd_test_byte60 |= unpack_left_shift_u32(src_p[63], 24u, 0xffu);

    return (0);
}

int fd_test_fd_test_init(struct fd_test_fd_test_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct fd_test_fd_test_t));

    return 0;
}

uint32_t fd_test_fd_test_fd_test_counter_encode(double value)
{
    return (uint32_t)(value);
}

double fd_test_fd_test_fd_test_counter_decode(uint32_t value)
{
    return ((double)value);
}

bool fd_test_fd_test_fd_test_counter_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t fd_test_fd_test_fd_test_byte8_encode(double value)
{
    return (uint32_t)(value);
}

double fd_test_fd_test_fd_test_byte8_decode(uint32_t value)
{
    return ((double)value);
}

bool fd_test_fd_test_fd_test_byte8_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t fd_test_fd_test_fd_test_byte32_encode(double value)
{
    return (uint32_t)(value);
}

double fd_test_fd_test_fd_test_byte32_decode(uint32_t value)
{
    return ((double)value);
}

bool fd_test_fd_test_fd_test_byte32_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t fd_test_fd_test_fd_test_byte60_encode(double value)
{
    return (uint32_t)(value);
}

double fd_test_fd_test_fd_test_byte60_decode(uint32_t value)
{
    return ((double)value);
}

bool fd_test_fd_test_fd_test_byte60_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}
