/**
 * @file fd_test.h
 *
 * @brief This header file was generated by cantools version 40.2.2 Tue Aug  4 16:27:12 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef FD_TEST_H
#define FD_TEST_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define FD_TEST_FD_TEST_FRAME_ID (0x7f2u)

/* Frame lengths in bytes. */
#define FD_TEST_FD_TEST_LENGTH (64u)

/* Extended or standard frame types. */
#define FD_TEST_FD_TEST_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define FD_TEST_FD_TEST_NAME "FD_TEST"

/* Signal Names. */
#define FD_TEST_FD_TEST_FD_TEST_COUNTER_NAME "fd_test_counter"
#define FD_TEST_FD_TEST_FD_TEST_BYTE8_NAME "fd_test_byte8"
#define FD_TEST_FD_TEST_FD_TEST_BYTE32_NAME "fd_test_byte32"
#define FD_TEST_FD_TEST_FD_TEST_BYTE60_NAME "fd_test_byte60"

/**
 * Signals in message FD_TEST.
 *
 * All signal values are as on the CAN bus.
 */
struct fd_test_fd_test_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t fd_test_counter;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t fd_test_byte8;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t fd_test_byte32;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint32_t fd_test_byte60;
};

/**
 * Pack message FD_TEST.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int fd_test_fd_test_pack(
    uint8_t *dst_p,
    const struct fd_test_fd_test_t *src_p,
    size_t size);

/**
 * Unpack message FD_TEST.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int fd_test_fd_test_unpack(
    struct fd_test_fd_test_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FD_TEST.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int fd_test_fd_test_init(struct fd_test_fd_test_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t fd_test_fd_test_fd_test_counter_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fd_test_fd_test_fd_test_counter_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fd_test_fd_test_fd_test_counter_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t fd_test_fd_test_fd_test_byte8_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fd_test_fd_test_fd_test_byte8_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fd_test_fd_test_fd_test_byte8_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t fd_test_fd_test_fd_test_byte32_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fd_test_fd_test_fd_test_byte32_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fd_test_fd_test_fd_test_byte32_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t fd_test_fd_test_fd_test_byte60_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fd_test_fd_test_fd_test_byte60_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fd_test_fd_test_fd_test_byte60_is_in_range(uint32_t value);


#ifdef __cplusplus
}
#endif

#endif
